server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cft
    username: cft
    password: cftpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

security:
  jwt:
    secret: 9wMp1c7do3N8d1vo90U8d3V1awtTTTymjDAOawywiZ28hvZT
    expiryMinutes: 120
