name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Test (Maven)
        run: ./mvnw -q -DskipTests=false -f backend/pom.xml test package || mvn -q -DskipTests=false -f backend/pom.xml test package

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "cft-backend"
          path: "backend"
          format: "HTML"
          out: "reports"

      - name: Upload dep-check report
        uses: actions/upload-artifact@v4
        with:
          name: depcheck-report
          path: reports

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t cft-backend:ci -f devops/docker/Dockerfile.backend .

      - name: Build frontend image
        run: docker build -t cft-frontend:ci -f devops/docker/Dockerfile.frontend .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "cft-backend:ci"
          format: 'table'
          exit-code: '0'

  zap-baseline:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.STAGING_URL }}
          rules_file_name: '.zap/rules.tsv'
        continue-on-error: true
